src/UniversalDashboard.UITest/Integration/Element.Tests.ps1
Url having problem is "home" not home 2 and "homepage" was missing UD-button to perform test.
=> Added HomePage2 UDButton & modified se-url

src/UniversalDashboard/Controls/src/image.ps1, src/UniversalDashboard/UniversalDashboardServer.psm1
Added Condition to Add Attiribute only if passed as parameter.
=> New Udimage fix

src/UniversalDashboard.UITest/Cmdlet/New-UDDashboard.Tests.ps1, src/UniversalDashboard.UITest/Integration/FontIcon.Tests.ps1, src/UniversalDashboard/Cmdlets/NewDashboardCommand.cs, src/UniversalDashboard/Help/New-UDDashboard.md, src/UniversalDashboard/Models/Dashboard.cs, src/client/package-lock.json, src/client/package.json, src/client/src/app/index.jsx, src/client/src/app/ud-dashboard.jsx, src/poshud/dashboard.ps1
Replace Font Awesome with modern line icons. 
Add Support for line-awesome icon style in UD.
You can choose between the default Font-Awesome or the new Line-Awesome Style, by using the new 
```powershell
-FontIconStyle Parameter in New-UDDashboard.
```
[Icons8 Line Awesome](https://github.com/icons8/line-awesome)
[![Build status](https://ci.appveyor.com/api/projects/status/9o60xjy52n651nto?svg=true)](https://ci.appveyor.com/project/AlonGvili/universal-dashboard-yju6o)
=> Add support for Icons8 line-awesome font icons.

src/UniversalDashboard.UITest/Integration/Page.Tests.ps1, src/UniversalDashboard/Cmdlets/NewPageCommand.cs, src/UniversalDashboard/Help/New-UDImage.md, src/UniversalDashboard/Help/New-UDPage.md, src/UniversalDashboard/Help/Remove-UDCookie.md, src/UniversalDashboard/Models/Page.cs, src/client/src/app/ud-dashboard.jsx, src/client/src/app/ud-navbar.jsx
Add new parameter `-DefaultHomePage` to New-UDPage Cmdlet.
This will set the first page that UD show on load and set the UD title bar linked to the home page.
[AppVeyor](https://ci.appveyor.com/project/AlonGvili/universal-dashboard-k5877#L834)
Fixes #363
=> Fix title bar should link to home page

src/UniversalDashboard.UITest/Integration/Card.Tests.ps1, src/UniversalDashboard/Controls/src/card.ps1, src/poshud/pages/card.ps1
Fixes #383 
now when selecting `-TextSize` parameter with a value of medium or large the card will display the content
=> Fix New-UDCard TextSize Parameter

src/client/src/app/ud-navbar.jsx
=> Remove Empty Div and Insert React Fragment instead

src/UniversalDashboard.UITest/Integration/ImageCarousel.Tests.ps1, src/UniversalDashboard.UITest/Manifest.Tests.ps1, src/UniversalDashboard/Cmdlets/NewImageCarouselCommand.cs, src/UniversalDashboard/Cmdlets/NewImageCarouselItemCommand.cs, src/UniversalDashboard/Help/New-UDImageCarousel.md, src/UniversalDashboard/Help/New-UDImageCarouselItem.md, src/UniversalDashboard/Models/ImageCarousel.cs, src/UniversalDashboard/Models/ImageCarouselItem.cs, src/UniversalDashboard/New-UDModuleManifest.ps1, src/client/.babelrc, src/client/package.json, src/client/src/app/services/render-service.jsx, src/client/src/app/ud-image-carousel.jsx, src/poshud/pages/card.ps1, src/poshud/pages/chart-updated.ps1
Add new image carousel component for ud.
This component will use 2 new commands
New-UDImageCarousel - for creating the main carousel container
New-UDImageCarouselItem - to create new slide for ImageCarousel 
I added tests and help files for the new command.
Will add demo page after build succeded.
preview:
=> New Image Carousel Component

src/UniversalDashboard.UITest/Integration/Input.Tests.ps1, src/UniversalDashboard/Cmdlets/ComponentCmdlet.cs, src/UniversalDashboard/Cmdlets/Inputs/NewInputCommand.cs, src/UniversalDashboard/Cmdlets/NewEndpointCommand.cs, src/UniversalDashboard/Constants.cs, src/UniversalDashboard/Controllers/ComponentController.cs, src/UniversalDashboard/Help/ConvertTo-JsonEx.md, src/UniversalDashboard/Help/New-UDEndpointInitialization.md, src/UniversalDashboard/Help/New-UDImageCarousel.md, src/UniversalDashboard/Help/New-UDImageCarouselItem.md, src/UniversalDashboard/Help/New-UDInput.md, src/UniversalDashboard/Help/Start-UDDashboard.md, src/UniversalDashboard/Models/Component.cs, src/UniversalDashboard/Models/Input.cs, src/UniversalDashboard/Models/ValidationErrorMessage.cs, src/UniversalDashboard/Models/ValidationErrorMessageAttribute.cs, src/UniversalDashboard/Services/DefaultComponentWriter.cs, src/UniversalDashboard/UniversalDashboardServer.psm1, src/client/src/app/ud-input-field.jsx, src/client/src/app/ud-input.jsx
=> Validation for UDInput. 

src/UniversalDashboard/Controls/src/card.ps1
Updated the New-UDCard function to have the option of making an image horizontal.
=> New-UDCard Horizontal

src/UniversalDashboard/Cmdlets/Charting/NewChartCommand.cs, src/UniversalDashboard/Models/Chart.cs, src/client/src/app/ud-chart.jsx
=> Add OnClick handler to New-UDChart

src/web.config
Remove headers disclosing technology stack used. #589
=> Remove X-Powered-By and Server header

src/UniversalDashboard/Controls/src/collapsible.ps1, src/client/src/index.html
Corrected spelling on accordion type for UDCollapsible.
=> Update collapsible to fix accordion type & add viewport tag for mobile users.

src/UniversalDashboard/Themes/DarkDefault.psd1
Adding a new "Default Dark" Them - Simple Dark Gray/Black with White Text
=> Default Dark

src/web.config
=> Comment out requestFiltering as it doesn't work on older IIS versions.

src/client/src/app/ud-grid-layout.jsx
=> Persist grid layout

src/UniversalDashboard.Materialize/Components/ud-navigation.jsx
=> Fix icon spacing

src/UniversalDashboard.Materialize/Components/tabs.jsx
Fixing #943
In issue #943, I post the result of the fix
=> Fix auto resize udinputs in tabs

src/UniversalDashboard.Materialize/Components/ud-select.jsx, src/UniversalDashboard.Materialize/Scripts/select.ps1
Fixing the bug in ud-select when using SelectGroup function.
result
=>  Fix ud-select selectGroup bug

src/UniversalDashboard.Materialize/Components/ud-input-field.jsx
fix the radio group placeholder problem.
fixing  #951
=> Fixing  #951 Radio group placeholder bug

src/UniversalDashboard.Materialize/Components/ud-navigation.jsx
add the width parameter to SideNav component
=> Fix width parameter not used in SideNav

src/UniversalDashboard/Execution/ScheduledEndpointManager.cs
This is to allow more than 10.
it should be added to a config file instead.
I gave up on finding out how to use a config file in aspnetcore :)
=> Changed the Threadcount to 100

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Adding Bug Report AND Feature Request Issue Templates.
=> Github Issue Templates: Bug and Feature Request

src/UniversalDashboard/Themes/Azure.psd1
added rounded boarders, added item,collapsible,paging styling. rounded the buttons styled buttons.  Styled radio button and check box two have azure colour.  Fixed an issue with the footer not having any margin-top space so no components hit the footer bar, made sidenav appear under the main navbar also applied azure theming to this as well, and finally the tabs, tabs are now azure theme.  Also added slight rounded boarder for images and float aligned left.
=> My Azure modified theme

src/UniversalDashboard/Cmdlets/NewEndpointScheduleCommand.cs, src/UniversalDashboard/Execution/ScheduledEndpointJob.cs, src/UniversalDashboard/Execution/ScheduledEndpointManager.cs, src/UniversalDashboard/Help/New-UDEndpointSchedule.md, src/UniversalDashboard/Models/EndpointSchedule.cs
This PR adds support for Consecutive and Repeat options for New-UDEndpointSchedule
=> Adds support for Consecutive & Repeat for New-UDEndpointSchedule

src/UniversalDashboard/Themes/Azure.psd1
Added pagination request on font color also done the same for export grid and refresh to keep in theme, sorted the sub header in side nav not being consistant with the other font color and size. Added default modal color and style, changed icon color for collapsibles so stand out a bit more.  All requests done.
=> 100% Complete Azure Theme

src/UniversalDashboard/Themes/Azure.psd1
issue raised now space under main navbar, now fixed.
=> Fixes issue with no space under navbar

src/UniversalDashboard.Materialize/Components/ud-grid.jsx, src/UniversalDashboard.Materialize/Components/ud-image-carousel.jsx
This will add support for changing the placeholder for the filter box when not using server side processing.
=> Fix for #134

src/UniversalDashboard/Themes/DarkDefault.psd1
Solves all the random whitespots and black text.
=> Visual upgrade, inspired by psDevUK

src/UniversalDashboard/Themes/Azure.psd1
psDevUK has fixed some, but i feel this has strayed away from the theme's name and main inspiration. I propose we change this back closer to original and add psDevUK's theme as a separate theme.
=> Reverting some of psdevuk's changes

src/UniversalDashboard.Materialize/Components/ud-navigation.jsx, src/UniversalDashboard/Cmdlets/NewSideNavCommand.cs, src/UniversalDashboard/Models/SideNav.cs
I'm not a good enough jsx hacker to do the conditional any better unfortunately.
=> Fix for issue #713

src/UniversalDashboard/Themes/DarkRounded.psd1
Adding some better stylying to other ud components, as in giving them the rounded edge effect. Also noticed the sidenav with sub items wasn't being styled colour wise correctly.
=> ADD MORE ROUNDED EDGES TO OTHER DASHBOARD UD COMPONENTS

examples/server-performance-dashboard.ps1
Fixes #5. Or at least, partially. I couldn't reproduce the error mentioned in the comment, and my searching just turned up [#52](https://github.com/ironmansoftware/universal-dashboard/issues/52), which has a cyclic reference with [this](https://github.com/adamdriscoll/poshprotools/issues/160). So, I assumed it isn't a problem anymore.
=> Fixed disk space chart minimum to 0

src/UniversalDashboard/Themes/DarkDefault.psd1
**Addresses**: 
https://github.com/ironmansoftware/universal-dashboard/issues/1115
https://github.com/ironmansoftware/universal-dashboard/issues/1110
=> Collapsible Header, Sidebar Collapsible Header Fixes

src/UniversalDashboard/Themes/Default.psd1
Adds white side nav dividers also fixes the background and lever colour on the switch lever when flicked to on state
=> Adds white side nav dividers, also fixes switch lever colour

src/UniversalDashboard/Themes/Default.psd1
https://github.com/ironmansoftware/universal-dashboard/issues/1154
=> Fixing Issue with Copyright

src/UniversalDashboard.Materialize/Components/ud-fab.jsx, src/UniversalDashboard.Materialize/Scripts/fab.ps1, src/UniversalDashboard/Themes/Default.psd1
UD-FAB fixing.
fab.ps1 TOLOWER on size param to make JSX happy.
For FAB Large AND Small needs to be set in JSX to do proper fab sizing!
https://react-materialize.github.io/react-materialize/?path=/story/components-fab--top
=> Ud-fab Small Size Fix!

src/poshud/pages/getting-started.ps1
I wasted to much time to admit ;)
=> Typo and parameter outside scriptblock

src/UniversalDashboard/Themes/DarkDefault.psd1
Changed the backgroundcolor to match the menubackupgroundcolor.
=> GridPagenumber now visible on active page

src/UniversalDashboard/Cmdlets/Select-UDElement.cs, src/UniversalDashboard/New-UDModuleManifest.ps1, src/UniversalDashboard/Server/DashboardHub.cs, src/client/src/app/ud-dashboard.jsx
Might have to fancify something, but tested and working.
=> Added select-udelement

src/UniversalDashboard/Cmdlets/Set-UDClipboard.cs, src/UniversalDashboard/New-UDModuleManifest.ps1, src/UniversalDashboard/Server/DashboardHub.cs, src/client/src/app/ud-dashboard.jsx
Might update at later stage to allow copying the specified clientside ID to the clipboard.
=> Added set-udclipboard. 

src/UniversalDashboard/Cmdlets/Set-UDClipboard.cs, src/UniversalDashboard/Server/DashboardHub.cs, src/client/src/app/ud-dashboard.jsx
=> Added support for toast on success to clipboard

src/UniversalDashboard/Themes/DefaultTight.psd1
=> Added DefaultTight theme

src/UniversalDashboard.Materialize/Scripts/table.ps1
See https://forums.universaldashboard.io/t/new-udtable-title-parameter-getting-class-of-card-title/1433 for info.
=> Add card-title class to udtable title.

src/UniversalDashboard.Materialize/Scripts/card.ps1
=> Add title-alignment to card

src/UniversalDashboard.UITest/Cmdlet/New-UDCard.Tests.ps1
to existing PR.... sorry.
https://github.com/ironmansoftware/universal-dashboard/pull/1245
=> No idea how to add files

src/UniversalDashboard/Cmdlets/Select-UDElement.cs, src/UniversalDashboard/Help/Select-UDElement.md, src/UniversalDashboard/Server/DashboardHub.cs, src/client/src/app/ud-dashboard.jsx
Also allows for anchors, for dynamic scrolling and adding "to top" buttons. 
Internal discussion if this functionality should be a separate function, however i see no use case where you would want to scroll somewhere on the page without moving the focus. 
Fixes #1286 
Tried to manually update the documentation aswell, prolly some errors there O:-)
=> Added "scrolltoelement" param to select

src/client/src/app/services/fetch-service.jsx
Note: the firefox tests keep on failing on me, prolly due to verison. Check the devops tests.
Seems like this function is only utilized by requeststate, and i've validated that this works wonderfully.
=> Fixes #1301

src/UniversalDashboard/Cmdlets/Select-UDElement.cs, src/UniversalDashboard/Help/Invoke-UDJavaScript.md, src/UniversalDashboard/Help/Select-UDElement.md, src/UniversalDashboard/Server/DashboardHub.cs, src/client/src/app/ud-dashboard.jsx
and document it for once...
Including documentation for invoke-udjavascript O:-)
=> Add -totop param to select-udelement

src/UniversalDashboard/Themes/DarkDefault.psd1
some dirty quick fixes, due to certain elements adding a "rgb(0,0,0)" style, i'll check up on that later.
=> Copy pasta of default theme with edits

examples/ping-grid.ps1, examples/servicenow-create-incident-form.ps1
+ PING Buddy!
+ ServiceDESK Entry Form
=> Youtube Demo Example Scripts

src/client/src/app/ud-element.jsx
Prolly used in some debugging?
=> Forgotten console.log

src/UniversalDashboard.Materialize/Components/ud-button.jsx
Should fix 978, and add support for set-udelement, get-udelement, hide-udelement.
Note: remove-udelement shouldn't work (haven't tested)
=> Fixes #978

src/UniversalDashboard.Materialize/Tests/textbox.tests.ps1, src/UniversalDashboard/Controls/src/textbox.ps1
https://github.com/ironmansoftware/universal-dashboard/issues/1330
=> Fix label overlap issue when value is provided

src/client/src/app/services/fetch-service.jsx
=> Fixes #1350

src/UniversalDashboard/Controls/src/event.ps1, src/UniversalDashboard/Help/Invoke-UDEvent.md, src/UniversalDashboard/New-UDModuleManifest.ps1
Added Invoke-UDEvent, with a single event currently supported "onClick".
Note: did not make this a default value, to prevent issues when we implement more events in the future.
=> Added invoke-udelement with documentation, fixes #616

src/UniversalDashboard/Controls/src/event.ps1
Adds new param "scheduled" to target scheduled endpoints to invoke.
=> Fixes #1381

CHANGELOG.md, src/UniversalDashboard.Materialize/Components/ud-checkbox.jsx
=> Fixes 50% of #1368

src/UniversalDashboard/Themes/Azure.psd1, src/UniversalDashboard/Themes/DarkDefault.psd1, src/UniversalDashboard/Themes/DarkRounded.psd1, src/UniversalDashboard/Themes/Default.psd1, src/UniversalDashboard/Themes/DefaultTight.psd1
This will resolve Issue [#1416](https://github.com/ironmansoftware/universal-dashboard/issues/1416) for Themes: **Azure, DarkDefault, DarkRounded, Default** and **DefaultTight.**
=> Fix for Issue #1416

src/UniversalDashboard/Controls/src/textbox.ps1, src/client/package-lock.json, src/client/src/app/ud-element.jsx
now it will remove the input element and the label and the parent element that is the div with the input-field className
before the fix its only remove the input element and create multiple parent elements with the same id
=> fixes #1378

examples/ping-grid-part3.ps1
add a new and extended version of the ping-grid example by adding subpages foreach server and graphs
=> extend ping example

CHANGELOG.md, src/UniversalDashboard/Services/ThemeService.cs, src/UniversalDashboard/Themes/DarkDefault.psd1, src/UniversalDashboard/Themes/Default.psd1, src/UniversalDashboard/Themes/DefaultTight.psd1
* Allow Specification of Font in Themes
* Change Tab Color and Font Slighty to be more uniform
=> Font, Tab Color Changes to Theme

src/UniversalDashboard/Themes/DarkDefault.psd1
Currently the new hardcoded definitions of classes in themeservice causes UD to crash on non-Default themes. This is a temp workaround.
=> Temp hotfix to view tabs

src/UniversalDashboard.Materialize/Components/ud-button.jsx, src/UniversalDashboard.Materialize/Scripts/button.ps1, src/UniversalDashboard/Help/New-UDButton.md
Made the -style have preference over the other "stylerelated" params.
=> Fixes #1453

src/UniversalDashboard.Materialize/Scripts/button.ps1
https://forums.universaldashboard.io/t/new-udbutton-styling-not-working-within-udgrid-after-upgrade-to-2-8-3/2144/6
=> Fix issue where backgroundcolor in grid

src/UniversalDashboard/Themes/DefaultTight.psd1
=> fixed wrong definition of FontFamily in DefaultThight theme

src/UniversalDashboard.MaterialUI/Components/table.jsx, src/UniversalDashboard.MaterialUI/Components/universal-dashboard.jsx, src/UniversalDashboard.MaterialUI/Scripts/table.ps1, src/UniversalDashboard.MaterialUI/Tests/driver.ps1, src/UniversalDashboard.MaterialUI/Tests/table.tests.ps1, src/UniversalDashboard.MaterialUI/build.ps1, src/UniversalDashboard.MaterialUI/dashboard.ps1, src/UniversalDashboard.MaterialUI/package-lock.json, src/UniversalDashboard.MaterialUI/package.json, src/UniversalDashboard/Models/PowerShellEndpoint.cs, src/UniversalDashboard/New-UDModuleManifest.ps1, src/UniversalDashboard/UniversalDashboard.psm1, src/client/src/app/services/universal-dashboard-service.jsx
Fixes #1089 
Fixes #1035
Fixes #994 
Fixes #290
=> Material table

src/UniversalDashboard.MaterialUI/Components/dynamic.jsx, src/UniversalDashboard.MaterialUI/Components/index.js, src/UniversalDashboard.MaterialUI/Components/universal-dashboard.jsx, src/UniversalDashboard.MaterialUI/Tests/table.tests.ps1, src/UniversalDashboard.MaterialUI/dashboard.ps1, src/UniversalDashboard/Cmdlets/NewDynamicCommand.cs, src/UniversalDashboard/New-UDModuleManifest.ps1
=> Implement dynamic.

src/UniversalDashboard.Common/Models/AbstractEndpoint.cs, src/UniversalDashboard.Common/Utilities/ObjectExtensions.cs, src/UniversalDashboard.MaterialUI/Components/table.jsx, src/UniversalDashboard.MaterialUI/Components/universal-dashboard.jsx, src/UniversalDashboard.MaterialUI/Scripts/table.ps1, src/UniversalDashboard.MaterialUI/Tests/table.tests.ps1, src/UniversalDashboard.MaterialUI/build.ps1, src/UniversalDashboard.MaterialUI/dashboard.ps1, src/UniversalDashboard/New-UDModuleManifest.ps1
=> Dynamic table

src/UniversalDashboard.MaterialUI/Components/select.jsx, src/UniversalDashboard.MaterialUI/Scripts/select.ps1, src/UniversalDashboard.MaterialUI/Tests/select.tests.ps1, src/UniversalDashboard.MaterialUI/dashboard.ps1
=> Implements multi-select

src/UniversalDashboard.Common/Models/Page.cs, src/UniversalDashboard.MaterialUI/Components/container.jsx, src/UniversalDashboard.MaterialUI/Components/framework/ud-page.jsx, src/UniversalDashboard.MaterialUI/Components/index.js, src/UniversalDashboard.MaterialUI/Scripts/container.ps1, src/UniversalDashboard.MaterialUI/Tests/page.tests.ps1, src/UniversalDashboard.MaterialUI/build.ps1, src/UniversalDashboard.MaterialUI/dashboard.ps1, src/UniversalDashboard/Cmdlets/NewPageCommand.cs, src/UniversalDashboard/New-UDModuleManifest.ps1, src/client/package-lock.json
Fixes #199
Fixes #192 
Fixes #715 
Fixes #1578 
Fixes #1577 
Fixes #1574 
Fixes #1172 
Fixes #1437
=> Changes to dynamic pages.

src/UniversalDashboard.UITest/Integration/Api.Tests.ps1, src/UniversalDashboard/Cmdlets/NewEndpointCommand.cs, src/UniversalDashboard/Controllers/ComponentController.cs
=> Fixes #1524

src/UniversalDashboard.Common/Models/Error.cs, src/UniversalDashboard.MaterialUI/Components/form.jsx, src/UniversalDashboard.MaterialUI/Components/framework/error-card.jsx, src/UniversalDashboard.MaterialUI/Components/index.js, src/UniversalDashboard.MaterialUI/Scripts/form.ps1, src/UniversalDashboard.MaterialUI/Tests/form.tests.ps1, src/UniversalDashboard.MaterialUI/UniversalDashboard.MaterialUI.psm1, src/UniversalDashboard.MaterialUI/build.ps1, src/UniversalDashboard.MaterialUI/dashboard.ps1, src/UniversalDashboard/Cmdlets/NewPageCommand.cs, src/UniversalDashboard/Execution/PowerShellExecutionService.cs, src/UniversalDashboard/New-UDModuleManifest.ps1, src/UniversalDashboard/Server/DashboardHub.cs, src/client/src/app/ud-element.jsx, src/poshud/dashboard.psm1
Fixes #1475 
Fixes #1298 
Fixes #282 
Fixes #1455
=> Form validation and better error messages.

src/UniversalDashboard.MaterialUI/Components/index.js, src/UniversalDashboard.MaterialUI/Components/slider.jsx, src/UniversalDashboard.MaterialUI/Scripts/slider.ps1, src/UniversalDashboard.MaterialUI/build.ps1, src/UniversalDashboard.MaterialUI/dashboard.ps1, src/UniversalDashboard/New-UDModuleManifest.ps1, src/poshud/dashboard.psm1
=> slider control.

src/UniversalDashboard.MaterialUI/Components/framework/ud-modal.jsx, src/UniversalDashboard.MaterialUI/dashboard.ps1, src/UniversalDashboard/Cmdlets/ShowModalCommand.cs, src/UniversalDashboard/Help/Show-UDModal.md, src/UniversalDashboard/Models/Modal.cs, src/poshud/dashboard.psm1
=> Modal, Fix docs.

src/UniversalDashboard.UITest/Integration/ScheduledEndpoint.Tests.ps1, src/UniversalDashboard/Cmdlets/NewEndpointCommand.cs, src/UniversalDashboard/Cmdlets/RemoveEndpointCommand.cs, src/UniversalDashboard/Execution/EndpointService.cs, src/UniversalDashboard/Execution/ScheduledEndpointManager.cs, src/UniversalDashboard/Interfaces/IEndpointService.cs, src/UniversalDashboard/Interfaces/ScheduledEndpointManager.cs, src/UniversalDashboard/New-UDModuleManifest.ps1
=> Fixes #1394

src/UniversalDashboard.Common/Interfaces/IExecutionService.cs, src/UniversalDashboard.UITest/Integration/ScheduledEndpoint.Tests.ps1, src/UniversalDashboard/Cmdlets/InvokeEndpointCommand.cs, src/UniversalDashboard/Constants.cs, src/UniversalDashboard/Controls/src/event.ps1, src/UniversalDashboard/Execution/EndpointService.cs, src/UniversalDashboard/Execution/ExecutionService.cs, src/UniversalDashboard/Execution/PowerShellExecutionService.cs, src/UniversalDashboard/Interfaces/IEndpointService.cs, src/UniversalDashboard/New-UDModuleManifest.ps1, src/UniversalDashboard/Server/Server.cs, src/UniversalDashboard/Services/DashboardService.cs
=> Invoke endpoint
