ironmansoftware/universal-dashboard

src/UniversalDashboard.UITest/Cmdlet/New-UDImage.Tests.ps1
src/UniversalDashboard/Controls/src/image.ps1

New-UDImage -Path parameter was not working after recent merge that resulted in $Attributes.'src' only being set if the -URL paramter was used.  This patch adds parameter sets to New-UDImage for the 2 usage scenarios and adds a test for the -path parameter.  I'm new to writing pester tests and am not sure if using $PSCommandPath will work for the test -Path value in your testing environment but it does work on my local system.

Fix for -Path parameter in New-UDImage

---

src/client/src/app/ud-input-field.jsx

Now when you select the year the window will not close, and I change the value from 7 years back to 50 by default.
Fixes #388

Disable auto close when year selected

---

src/UniversalDashboard.UITest/Integration/Chart.Tests.ps1
src/UniversalDashboard/Cmdlets/Charting/NewChartCommand.cs
src/UniversalDashboard/Cmdlets/Charting/NewMonitorCommand.cs
src/UniversalDashboard/Cmdlets/NewLinkCommand.cs
src/UniversalDashboard/Help/New-UDChart.md
src/UniversalDashboard/Help/New-UDLink.md
src/UniversalDashboard/Help/New-UDMonitor.md
src/UniversalDashboard/Help/Out-UDGridData.md
src/UniversalDashboard/Models/Chart.cs
src/UniversalDashboard/Models/Monitor.cs
src/client/.babelrc
src/client/package.json
src/client/src/app/ud-chart.jsx
src/client/src/app/ud-monitor.jsx
src/client/src/app/ud-navbar.jsx
src/client/webpack.config.js
src/poshud/pages/chart-updated.ps1
src/poshud/pages/charts.ps1

Add 2 new properties for chart and monitor: Width & Height
You can use those parameter with values like 300px, 80vw, 100%
Preview
And i add new test for custom chart size, and update the help for the new parameters.

Fix add support for chart and monitor custom size

---

src/UniversalDashboard/Controls/src/card.ps1

udtheme  was never applied to UDCard as a predefined Style overrided the CSS.

Removed forced style on udcard - #529

---

src/UniversalDashboard/UniversalDashboard.psm1

So [DashboardColor] can be used directly instead of referencing [UniversalDashboard.Models.DashboardColor]

Add type accelerator for DashboardColor

---

src/UniversalDashboard.Materialize/Components/ud-select.jsx

Fix for New-UDSelectOption "-Selected" param does not actually select #959
result

Fixing -Selected in New-UDSelect

---

examples/server-performance-dashboard.ps1

The original version Get-Process | Out-UDGridData is inefficient and take a long time to generate. By limiting the properties sent to Out-UDGridData, process list is loaded significantly faster.

New-UDGrid process section performance increase.

---

src/UniversalDashboard/Server/DashboardHub.cs

This is just a quick modification to add which EventId is being called for instance when running a -OnChange { script block }
However when running this you will get the EventId for the "endpoint" running it, so for instance.
New-UDCheckbox -Id 'Group1' -Label 'Group 1' -OnChange {
Show-UDToast -Message "You clicked on $EventId and toggled it to $EventData" -duration 8000
}
This can be useful when you build up a lot of checkboxes on a page dynamically and don't want to iterate over all of them to find out which one was changed...

Update to add which EventId was called

---

docker/dockerfile
docker/startdashboard.ps1

Added a Simple dockerfile directory. This dockerfile is based on Microsofts latest ubuntu PowerShell docker container.
DockerFile copies a simple script that upon execution of the container will download Universal Dashboard Community module and start the default dashboard on an exposed port 8080.
In the future, it would be nice to separate this from the Microsoft container AND install UD as a dockerfile run step and note require a separate .ps1 file - but this works for now! 
**How to Run**
Browse to the docker folder, we'll build with a . reference so the dockerfile and the startdashboard.ps1 will need to be in the current directory.
```cmd
docker build . --tag=universaldashboarddemo
docker run -it -p 8080:8080 universaldashboarddemo:latest 
```

Adding Dockerfile for UD Community Demo

---

src/UniversalDashboard.Materialize/Components/ud-button.jsx

If the Text property is empty or the button type is floating the marginRight will be removed
Fix #1027

Remove icon margin right inside a button

---

src/UniversalDashboard/Cmdlets/Inputs/NewInputFieldCommand.cs

This will make sure that new-udinputfield -type select always gets a defaultvalue if it contains more than 0 values so it will not be null anymore.

Fix for #694

---

src/UniversalDashboard/Controls/src/textbox.ps1

Optimally the attribute should have no value.

Add param to autofocus textbox on load. #564

---

src/UniversalDashboard/Themes/Default.psd1

PR for: https://github.com/ironmansoftware/universal-dashboard/issues/1031 - Changed the default blue to match the spec on Material UI since we weren't REALLY married to the existing blue: https://material-ui.com/customization/color/#color-tool
* Specifically utilizing these shades of blue:
* Primary:  ``#3f51b5``
* Secondary ``#2c387e``
* Main Font Color is new ``#111111`` instead of ``#000000`` for eye strain ease reading black text on white background.
* Adding 50px padding to main - this prevents elements to going from screen ends and makes it look much nicer. This does reduce usable screen space - but in this case it makes default dashboards look much sexier.
* ``#EEEEEE`` light gray background color seperates dashboard elements from background and gives a nice "3d" look.
With no …

Default theme update - Padding, Background Color, MaterialUI Color Spec

---

src/UniversalDashboard/Themes/Default.psd1

Alright, hear me out... 
After submitting the recent PR for the default theme improvements - I was playing around with SideNav. Applying the Indigo [Material-UI Color](https://material-ui.com/customization/color/) as the background behind white text looks amazing. I propose making this the new default! It very much looks like a cool "hipster" web application.
**Note** - Besides color change: 
collapsible-header and subheader have been given 'font-size' = 'large' to help make them standout against the normal elements.
Works for FIXED and non fixed.
**ScreenShots**

New and Improved Indigo Themed Sidenav

---

src/UniversalDashboard/Themes/Azure.psd1

img appear in-between ud-cards because of it. 
Other themes do not have their img tag set to float.

img with float parameter causing layout issues.

---

src/UniversalDashboard/Themes/Default.psd1

Addressing: https://github.com/ironmansoftware/universal-dashboard/issues/1071
Used Material-UI Color:
Background Color: `#8c9eff`
ForeGround Progress Color: `#3f51b5` - this is the default primary "Indigo"
Still utilizing that: https://material-ui.com/customization/color/

ProgressBar Color Fix

---

src/UniversalDashboard.Materialize/Components/ud-footer.jsx
src/UniversalDashboard/Cmdlets/NewFooterCommand.cs
src/UniversalDashboard/Models/Footer.cs
src/UniversalDashboard/Themes/Default.psd1

* Some bugs on footer color assignment since the first commit :)
* Applied Footer Styling to Footer and Copyright DIV
```powershell
$Footer = New-UDFooter -Copyright 'Copyright - "The Internet"' -BackgroundColor "Red" -FontColor "Purple"
```
```powershell
$Footer = New-UDFooter -Copyright 'Copyright - "The Internet"' -BackgroundColor "Transparent" -FontColor "#e91e63"
```

Copyright color fixes

---

src/UniversalDashboard.Materialize/Scripts/collapsible.ps1
src/UniversalDashboard/Models/DashboardColor.cs
src/UniversalDashboard/Themes/Default.psd1

* Adding "Transparent" String handling to Dashboard Color Class
* Set Default $BackgroundColor  of UDcollapsible to 'Transparent'
Addresses: https://github.com/ironmansoftware/universal-dashboard/issues/1149
**Testing - Note you can still of course specify a background, but it looks good without specfiying a background since the default is now transparent.
```powershell
New-UDCollapsible -Popout -Items {
New-UDCollapsibleItem -Title "Get-UDfsfaElement" -Content {
New-UDTextbox -Label "Enter srome text" -Id 'MyTextbox'
New-UDButton -Text 'Get the text' -OnClick {
Show-UDToast -Message (Get-UDElement -Id 'MyTextbox').Attributes['value']
}
}
New-UDCollapsibleItem -Title "THE BLUE BOY" -Content {
New-UDTextbox -Label "Enter some text" -Id 'MyTextbox'
New-UDButton -Text 'Get the text' -OnClick …
```

Collapsible Fixes for issue 1149

---

src/UniversalDashboard/Controllers/ComponentController.cs

Allows for file upload via REST -api.
Note: the original file name is not included in the request. 
However, added support for "wildcard" contenttype: ie: file/* and image/* in order to reconstruct. 
Readable from the HTTP Request in Endpoint. 
See 
https://hastebin.com/tediyiqahi.bash 
for Powershell Example.
For uploading files -contenttype must be specified according to pattern.

Fixes #748

---

src/UniversalDashboard/Cmdlets/NewEndpointCommand.cs
src/UniversalDashboard/Controllers/ComponentController.cs
src/UniversalDashboard/Models/Endpoint.cs

By allowing you to specify a switch on POST endpoints if fileupload should be allowed. Default disabled.
If you upload a file on a non-fileuploadaccepting endpoint, no errors will be presented, but no data is processed from the body or passed to the scriptblock.
And yes... i did test the api integration tests this time O:-)

Added security for REST Fixes #1262

---

src/UniversalDashboard/Cmdlets/Invoke-UDJavaScript.cs
src/UniversalDashboard/New-UDModuleManifest.ps1
src/UniversalDashboard/Server/DashboardHub.cs
src/client/src/app/ud-dashboard.jsx

Allows for custom javascript executed clientside on demand. 
See https://github.com/BoSen29/Discussion/blob/master/invoke-udjavascript.ps1 for example usage.
The javascript "codeblock" is passed as string, and then ran clientside.
Should be able to fixe https://forums.universaldashboard.io/t/image-to-fill-screen-no-edge-borders/1593/3 using this.

Added invoke-udjavascript command
